/**
 * HTML to PDF API v7.0.0 — API Test Suite
 *
 * Usage: node test_api.js [base_url]
 * Default: http://localhost:3000
 */
const axios = require("axios");

const BASE_URL = process.argv[2] || "http://localhost:3000";
let passed = 0;
let failed = 0;

async function test(name, fn) {
  try {
    await fn();
    console.log(`  ✅ ${name}`);
    passed++;
  } catch (err) {
    console.error(`  ❌ ${name}: ${err.message}`);
    failed++;
  }
}

function assert(condition, message) {
  if (!condition) throw new Error(message || "Assertion failed");
}

async function run() {
  console.log(`\n🧪 HTML to PDF API v7.0.0 — Test Suite`);
  console.log(`   Target: ${BASE_URL}\n`);

  // ─── Root & Info ──────────────────────────────────────────
  console.log("📋 Root & Info");

  await test("GET / returns v7.0.0", async () => {
    const { data } = await axios.get(`${BASE_URL}/`);
    assert(data.version === "7.0.0", `Expected v7.0.0, got ${data.version}`);
    assert(data.status === "running", "Status should be running");
  });

  await test("GET /templates lists templates with preview", async () => {
    const { data } = await axios.get(`${BASE_URL}/templates`);
    assert(data.templates.length >= 6, "Should have at least 6 templates");
    assert(data.templates[0].has_preview === true, "Should have preview flag");
  });

  // ─── Health Check ─────────────────────────────────────────
  console.log("\n❤️  Health Check");

  await test("GET /health returns system status", async () => {
    const { data, status } = await axios.get(`${BASE_URL}/health`);
    assert(status === 200 || status === 503, "Should return 200 or 503");
    assert(data.version === "7.0.0", "Health should show v7.0.0");
    assert(data.system, "Should have system info");
    assert(data.process, "Should have process info");
    assert(data.browser !== undefined, "Should have browser status");
  });

  // ─── Security Headers ────────────────────────────────────
  console.log("\n🛡️  Security Headers");

  await test("Helmet security headers present", async () => {
    const { headers } = await axios.get(`${BASE_URL}/`);
    assert(
      headers["x-content-type-options"] === "nosniff",
      "Missing X-Content-Type-Options",
    );
    assert(headers["x-frame-options"], "Missing X-Frame-Options");
    assert(headers["strict-transport-security"], "Missing HSTS");
  });

  // ─── PDF Generation ──────────────────────────────────────
  console.log("\n📄 PDF Generation");

  let testPdfFilename;

  await test("POST /cetak_struk_pdf basic HTML", async () => {
    const { data } = await axios.post(`${BASE_URL}/cetak_struk_pdf`, {
      html_content: "<h1>Test PDF v7</h1><p>Generated by automated test</p>",
      page_size: "a4",
    });
    assert(data.status === "success", "Should succeed");
    assert(data.file_url, "Should have file_url");
    testPdfFilename = data.filename;
  });

  await test("POST /generate with invoice template", async () => {
    const { data } = await axios.post(`${BASE_URL}/generate`, {
      template: "invoice",
      data: {
        invoice_no: "TEST-001",
        company_name: "Test Corp",
        items: [{ name: "Item", qty: 1, price: 100000 }],
      },
    });
    assert(data.status === "success", "Should succeed");
  });

  await test("GET /templates/invoice/preview generates preview", async () => {
    const { data } = await axios.get(`${BASE_URL}/templates/invoice/preview`);
    assert(data.status === "success", "Should succeed");
    assert(data.template === "invoice", "Should be invoice template");
    assert(data.file_url, "Should have file_url");
  });

  await test("POST /cetak_struk_pdf with QR + Barcode", async () => {
    const { data } = await axios.post(`${BASE_URL}/cetak_struk_pdf`, {
      html_content: "<h1>QR+Barcode Test</h1>",
      page_size: "a4",
      qr_code: { text: "TEST-QR-001", position: "top-right", width: 80 },
      barcode: {
        text: "TEST123456",
        type: "code128",
        position: "bottom-center",
      },
    });
    assert(data.status === "success", "Should succeed");
  });

  // ─── QR Code & Barcode ────────────────────────────────────
  console.log("\n📱 QR Code & Barcode");

  await test("POST /qr-code generates QR", async () => {
    const { data } = await axios.post(`${BASE_URL}/qr-code`, {
      text: "https://test.com",
      format: "base64",
    });
    assert(data.status === "success", "Should succeed");
    assert(data.base64, "Should have base64");
  });

  await test("POST /barcode generates barcode", async () => {
    const { data } = await axios.post(`${BASE_URL}/barcode`, {
      text: "1234567890",
      type: "code128",
      format: "base64",
    });
    assert(data.status === "success", "Should succeed");
  });

  // ─── Security Features ───────────────────────────────────
  console.log("\n🔐 Security Features");

  if (testPdfFilename) {
    await test("POST /encrypt-pdf encrypts with AES-256", async () => {
      const { data } = await axios.post(`${BASE_URL}/encrypt-pdf`, {
        filename: testPdfFilename,
        password: "test_password_123",
      });
      assert(data.status === "success", "Should succeed");
      assert(data.encryption === "AES-256", "Should use AES-256");
    });

    await test("POST /sign-pdf with inline signature", async () => {
      const tinyPng =
        "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg==";
      const { data } = await axios.post(`${BASE_URL}/sign-pdf`, {
        filename: testPdfFilename,
        signature_base64: tinyPng,
        position: "bottom-right",
        width: 80,
        height: 40,
      });
      assert(data.status === "success", "Should succeed");
    });

    await test("POST /secure/generate creates signed URL", async () => {
      const { data } = await axios.post(`${BASE_URL}/secure/generate`, {
        filename: testPdfFilename,
        expiry_minutes: 5,
      });
      assert(data.status === "success", "Should succeed");
      assert(data.signed_url, "Should have signed_url");
      assert(data.expires_at, "Should have expires_at");
    });
  }

  // ─── File Management ─────────────────────────────────────
  console.log("\n📂 File Management");

  await test("GET /files lists files", async () => {
    const { data } = await axios.get(`${BASE_URL}/files`);
    assert(data.status === "success", "Should succeed");
    assert(Array.isArray(data.files), "Should have files array");
  });

  // ─── Admin ───────────────────────────────────────────────
  console.log("\n🔐 Admin");

  await test("POST /admin/login with default credentials", async () => {
    const { data } = await axios.post(`${BASE_URL}/admin/login`, {
      username: "admin",
      password: "admin123",
    });
    assert(data.status === "success", "Should succeed");
    assert(data.token, "Should return JWT token");
  });

  // ─── 404 Handler ──────────────────────────────────────────
  console.log("\n🚦 Error Handling");

  await test("GET /nonexistent returns 404", async () => {
    try {
      await axios.get(`${BASE_URL}/nonexistent_route_xyz`);
      throw new Error("Should have returned 404");
    } catch (err) {
      assert(err.response && err.response.status === 404, "Should be 404");
    }
  });

  // ─── Summary ──────────────────────────────────────────────
  console.log(`\n${"─".repeat(50)}`);
  console.log(
    `📊 Results: ${passed} passed, ${failed} failed, ${passed + failed} total`,
  );
  console.log(`${"─".repeat(50)}\n`);

  process.exit(failed > 0 ? 1 : 0);
}

run().catch((err) => {
  console.error("\n💥 Test runner crashed:", err.message);
  process.exit(1);
});
